### ISSUE TITLE
SD-Datenformate Festzurren. 

### ISSUE THREAD

**Issue by MaxBaex** [larus-breeze/sw_sensor_algorithms#5]
Das Datenformat in:  https://github.com/larus-breeze/sw_sensor_algorithms/blob/main/NAV_Algorithms/data_structures.h und https://github.com/larus-breeze/sw_sensor_algorithms/blob/main/NAV_Algorithms/GNSS.h
ändert sich ab und zu, was dazu führt dass das Simulieren via: https://github.com/larus-breeze/SIL_flight_sensor_emulator mit "alten Flugdaten" in einem anderen Format ohne Umwandlung nicht funktioniert.  
Daher sollte das Dateiformat "eingefroren" werden. Alte Flugdaten sollten dannach in dieses Format konvertiert werden. 
Alternativ wäre ein Python Konverter denkbar, der im Kopilierprozess eingebunden ist und basierend auf "measurement_data_t" einen Datenbeschreibungsheader generiert der dann beim Auswerten mit dem SIL, o.Ä. eingelesen wird.  

**measurement_data_t:** 
- Define "WITH_LOWCOST_SENSORS" inkl. der Low Cost Sensorparameter entfernen. 
- Define "WITH_DENSITY_DATA" und diese Daten immer in der Datenstruktur vorhalten auch wenn diese Daten nicht geloggt werden. 
- #if INCLUDING_NANO   in GNSS.h immer mitloggen und Define entfernen. 

Beobachtete Formate: 
.f37
.f50
.f105
.f107
.f118

Einigebeschreibungen sind in https://github.com/larus-breeze/SIL_flight_sensor_emulator/tree/master/sensor_data_analyzer    andere sind hier: https://github.com/larus-breeze/sw_sensor_algorithms/tree/Klaus_work
Ich denke die Formatbeschreibungen im textfile format sollten alle hier liegen: https://github.com/larus-breeze/sw_sensor_algorithms/

**Comment by realtimepeople** [comment]
Done. We use *.f37 for the time being.
